### ISSUE TITLE
Question: How to run tests and see only the failing scenarios?

### ISSUE THREAD

**Issue by szabgab** [pherkin/test-bdd-cucumber-perl#176]
Right now if I run pherkin I see all the output.

If I run `prove` I only see some generic information:

```
examples/calculator/features/basic.feature .. Failed 1/82 subtests 

Test Summary Report
-------------------
examples/calculator/features/basic.feature (Wstat: 0 Tests: 82 Failed: 1)
  Failed test:  18
Files=1, Tests=82,  1 wallclock secs ( 0.47 usr  0.02 sys +  0.51 cusr  0.02 csys =  1.02 CPU)
Result: FAIL
```

If I runt `prove -v` then  I see all details of the error:
```
not ok 18 - In Then the display should show 4567
# Failed test 'In Then the display should show 4567'
# at /opt/perl-5.30.1/lib/5.30.1/TAP/Parser/IteratorFactory.pm line 217.
# 
#   in step at examples/calculator/features/basic.feature line 36.
#     ok - Starting to execute step: the display should show 4567
#     not ok 1 - Calculator display as expected
#     #   Failed test 'Calculator display as expected'
#     #   at /home/gabor/cpan/test-bdd-cucumber-perl/examples/calculator/features/step_definitions/calculator_steps.pl line 94.
#     #          got: '456'
#     #     expected: '4567'
#     1..2
#     # Looks like you failed 1 test of 2.

```

but also all the successful cases in which I am not interested.

(The specific error above was created just for illustration)

**Comment by ehuelsmann** [comment]
The short answer: No, there isn't.

The longer answer: I'm not happy about the error output: it's too long and not clear what it means. So, your recent activity has me looking into solving this.

The text of an error now looks like:
```plain
# Failed test 'Given a step with step function that calls die()'
# at t/pherkin/match-only/match.feature line 13.
#     not ok - Step ran to completion
#     # Failed test 'Step ran to completion'
#     # at lib/Test/BDD/Cucumber/Executor.pm line 639.
#     # Exception: 
#     # This step function calls die() at /home/ehuelsmann/test-bdd-cucumber-perl/t/pherkin/match-only/step_definitions/match_steps.pl line 9.
#     1..1
#     # Looks like you failed 1 test of 1.
```

Note that the error is now reported to be in the feature file, including a specific line, right at the top level, instead of being reported at `TAP::Parser::IteratorFactory` line 217. I feel that's a good improvement for clarity.

However, this does not solve the problem you'e pointed out where output is only available when prove runs with the `-v` option. I think I can use a bit of help here: when using `Test::More`'s `ok`, the output includes the error location. This library can't use Test::More, directly, because it's the `Test2` equivalent, using its `context()`. Calling `$ctx->fail(...)` doesn't seem to have the same effect (that it prints the error location, I mean).

I'll ask Chad about this too.

**Comment by ehuelsmann** [comment]
@szabgab, with some help from @exodist, I've been able to resolve this problem in the Pherkin `prove` integration.

**Comment by szabgab** [comment]
Thanks.

`pherkin` shows the error nicely, but `prove` does not do it yet. Would it be possible to add that to `prove` as well?

**Comment by ehuelsmann** [comment]
That's correct: it's fixed, but in the as of yet unreleased version 0.77 which I'm releasing while typing this.
