### ISSUE TITLE
Redispatching rules with data isn't working as documented

### ISSUE THREAD

**Issue by pplu** [pherkin/test-bdd-cucumber-perl#182]
Hi,

Lots of the rules I write are used in different situations (When, Then, Given). When I want to interpret data in them, I run into problems. From following the manual (https://metacpan.org/pod/distribution/Test-BDD-Cucumber/lib/Test/BDD/Cucumber/Manual/Steps.pod#Re-using-step-definitions), I got to:
```
Then qr/file (.*?) is/, sub($c) {
  my $path = $1;
  my $row = $c->data->[0];
  [...]
};
When qr/file (.*?) is/, sub($c) {
  $c->dispatch('Then', $c->text, $c->data); 
};
```
When this gets used as:
```
   When t/files/x is
    | mode |
    | 755  |
````

I get an exception in `Executor.pm`:
```
Can't use an undefined value as an ARRAY reference at Test/BDD/Cucumber/StepContext.pm line 417.
```

I've taken a look at the dispatch method, and its signature doesn't look to match with what the documentation states (https://metacpan.org/source/EHUELS/Test-BDD-Cucumber-0.77/lib%2FTest%2FBDD%2FCucumber%2FExecutor.pm#L569)

Is this feature not documented correctly? Or am I doing something wrong?

**Comment by ehuelsmann** [comment]
Hi,

Thanks for taking the time to log your issue. The dispatch method you're calling isn't the one you found and linked to. Instead, the dispatch method you're calling is the  one in the StepContext: https://metacpan.org/release/Test-BDD-Cucumber/source/lib/Test/BDD/Cucumber/StepContext.pm#L316.

To be honest, I'm not 100% sure you're using the feature incorrectly or that there's a bug in the code: you're passing `$c->data` into the step, which is an array of hashes. This means that the outer `if` at https://metacpan.org/release/Test-BDD-Cucumber/source/lib/Test/BDD/Cucumber/StepContext.pm#L335 *is* being run, but the inner `if` is not. Because of that, the `columns` attribute isn't initialized and the code at https://metacpan.org/release/Test-BDD-Cucumber/source/lib/Test/BDD/Cucumber/StepContext.pm#L417 is generating an exception.

From looking at the code, I'd say that columns should be initialized from `%{$data->[0]}` (if `@$data` has at least one element).

The change to do that would be simple enough, but then the documentation which says you can pass `{ some => 'data' }` makes no sense...

**Comment by pplu** [comment]
Hi,

   Thanks for your response! The original thing I was pursuing comes to be: how can I redispatch between steps conserving $c->data from the original step? 
   From what I've understood from your answer, I see a way to redispatch when the step is:
```
When file /x is
   | mode | owner |
   | 755  | pplu  |
```
we would use: `$c->dispatch(...., $c->data->[0])`
I don't see a way to redispatch if the step is:
```
When file /x is
   | x | y |
   | 3 | 4 |
   | 7 | 6 |
```

I finally found a way around the redispatch, which also generates a bit more compact code. I started doing the following:
```
$_ = sub ($c) {
  ...
};
Given qr/file (.*) is/, $_;
When qr/file (.*) is/, $_;
```
And that finally evolved into:

```
sub declare_steps ($qr, $sub) {
  Given $qr, $sub;
  Then  $qr, $sub;
  When  $qr, $sub;
}
declare_steps qr/file (.*) is/, sub ($c) {
  ...
}
```
since I use the same constructs in Given, Then and When steps

I have my needs solved without modifying the Test::BDD::Cucumber, but it is possible that the dispatch API has a small lacking for data with multiple rows.

Thank you for your help and this lovely Test module :heart:

**Comment by ehuelsmann** [comment]
@pplu , you don't need to declare the same sub on each of the keywords Given/When/When. Instead, you can use the `Step` keyword as swiftly mentioned in https://github.com/pherkin/test-bdd-cucumber-perl/blob/master/lib/Test/BDD/Cucumber/Manual/Steps.pod#starting-off
